base_dir/apps/urls.py
from django.urls import path
from . import views

app_name = 'apps'

urlpatterns = [
    path('parking_creation_form/', views.ParkingSpaceCreationFormView.as_view(), name='parking_creation_form'),

    path('parking_space_history/<int:parking_space_id>', views.parking_space_history, name='parking_space_history'),

    path('driver_register_form/', views.DriverRegisterFormView.as_view(), name='driver_register_form'),

    path('saving_driver/', views.saving_driver, name='saving_driver'),

    path('autos_register_form/', views.AutosRegisterFormView.as_view(), name='autos_register_form'),

    path('saving_autos/', views.saving_autos, name='saving_autos'),

    path('parking_assignment_form/', views.ParkingAssignmentFormView.as_view(), name='parking_assignment_form'),

    path('saving_parking_place/', views.saving_parking_place, name='saving_parking_place'),

    path('occupied_parking_spaces/', views.occupied_parking_spaces, name='occupied_parking_spaces'),

    path('registered_drivers/', views.registered_drivers, name='registered_drivers'),
    
    path('driver_search/', views.driver_search, name='driver_search'),

    path('registered_autos/', views.registered_autos, name='registered_autos'),

    path('plate_search/', views.plate_search, name='plate_search'),

    path('pre_finish/<int:parking_space_id>', views.pre_finish, name='pre_finish'),

    path('finish/<int:parking_space_id>/<int:autos_id>', views.finish, name='finish'),
    
    path('', views.main_page, name='main_page'),
]

base_dir/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls'), name='apps'),
]

base_dir/templates/automobile_form.html
<form action="{% url "apps:automobile_register" %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar">
</form>

base_dir/templates/autos_register_form.html
{% extends "base_parking.html" %}

{% block content %}
    {% if error %}
        {{ error }}
    {% else %}
        <form action="{% url "apps:saving_autos" %}" method="post">
            {% csrf_token %}
            <span>Nome/CPF do motorista: {{ form.driver_doc }}</span><br>
            <span>Modelo: {{ form.model }}</span><br>
            <span>Placa: {{ form.autos_plate }}</span><br>
            <input type="submit" value="Enviar">
        </form>
    {% endif %}
{% endblock content %}

base_dir/templates/base_parking.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Estacionamento do Bosque {% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% block css %}{% endblock css %}
</head>
<body>
    <header>
        <h1>Estacionamento do Bosque</h1>
    </header>
    <nav>
        <a href="{% url "apps:driver_register_form" %}">Cadastrar motorista</a>
        <a href="{% url "apps:registered_drivers" %}">Motoristas cadastrados</a>
        <a href="{% url "apps:autos_register_form" %}">Cadastrar veículo</a>
        <a href="{% url "apps:registered_autos" %}">Veículos cadastrados</a>
        <a href="{% url "apps:parking_assignment_form" %}">Cadastrar entrada</a>
        <a href="{% url "apps:main_page" %}">Vagas desocupadas</a>        
        <a href="{% url "apps:occupied_parking_spaces" %}">Vagas ocupadas</a>
        <a href="{% url "apps:parking_creation_form" %}">Cadastrar vagas</a>
    </nav>
    <main>
        {% block content %}{% endblock content %}          
    </main>
</body>
</html>

base_dir/templates/car_form.html
<form action="{% url "apps:car_register" %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Enviar">
</form>

base_dir/templates/driver_register_form.html
{% extends "base_parking.html" %}

{% block content %}
    {% if register_error %}
        {{ register_error }}
    {% elif cpf_error %}
        {{ cpf_error }}
        <form action="{% url "apps:saving_driver" %}" method="post">
            {% csrf_token %}
            <span>Nome: {{ form.driver_name }}</span><br>
            <span>Mensalista: {{ form.monthly }}</span><br>
            <span>CNH: {{ form.cnh }}</span><br>
            <span>CPF: {{ form.cpf }}</span><br>
            <span>Documento: {{ form.file_upload }}</span><br>
            <input type="submit" value="Enviar">
        </form>
    {% else %}
        <form action="{% url "apps:saving_driver" %}" method="post">
            {% csrf_token %}
            <span>Nome: {{ form.driver_name }}</span><br>
            <span>Mensalista: {{ form.monthly }}</span><br>
            <span>CNH: {{ form.cnh }}</span><br>
            <span>CPF: {{ form.cpf }}</span><br>
            <span>Documento: {{ form.file_upload }}</span><br>
            <input type="submit" value="Enviar">
        </form>
    {% endif %}    
{% endblock content %}

base_dir/templates/driver_search.html
{% extends "base_parking.html" %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/driver_search.css" %}">
{% endblock css %}
{% block content %}
    <h2>Motoristas cadastrados</h2>
    <section>
        {% for driver in drivers %}
            <div id="driver_search">
                <span>Nome: {{ driver.driver_name }}</span>
                <span>Mensalista: {{ driver.monthly }}</span>
                <span>CNH: {{ driver.cnh }}</span>
                <span>CPF: {{ driver.cpf }}</span>
            </div>
        {% endfor %}
    </section>
{% endblock content %}

base_dir/templates/main_page.html
{% extends "base_parking.html" %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/main_page.css" %}">
{% endblock css %}

{% block content %}
    <h2>Vagas disponíveis</h2>
    <section>
        {% for parking in unoccupied_parking_spaces %}
            <div id="parking_spaces">
                <a href="{% url "apps:parking_space_history" parking.id %}"><span>Vaga {{ parking.id }}</span></a>
            </div>
        {% endfor %}
    </section>
{% endblock content %}

base_dir/templates/occupied_parking_spaces.html
{% extends "base_parking.html" %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/occupied_parking_spaces.css" %}">
{% endblock css %}

{% block content %}
    <h2>Vagas ocupadas</h2>
    <section>
        {% for parking in occupied_parking_spaces %}
            <div id="parking_spaces">
                <span>Vaga {{ parking.id }}</span>
                <span>Veículo: {{ parking.occupied_by }}</span>
                <span>Horário de entrada: {{ parking.occupied_by.checkin_datetime }}</span>
                <a href="{% url "apps:pre_finish" parking.id %}">Finalizar</a>
            </div>
        {% endfor %}
    </section>
{% endblock content %}

base_dir/templates/parking_assignment_form.html
{% extends "base_parking.html" %}

{% block content %}
    <form action="{% url "apps:saving_parking_place" %}" method="post">
        {% csrf_token %}
        <span>Vaga: {{ form.parking_places }}</span><br>
        <span>Ocupada: {{ form.occupied }}</span><br>
        <span>Veículo: {{ form.occupied_by }}</span><br>
        <input type="submit" value="Enviar">
    </form>
{% endblock content %}

base_dir/templates/parking_space_history.html
{% extends "base_parking.html" %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/main_page.css" %}">
{% endblock css %}

{% block content %}
    <h2>Histórico de ocupação</h2>
    <section>
        {% for auto in history %}
            {{ auto }}<br>
        {% endfor %}
    </section>
{% endblock content %}

base_dir/templates/plate_search.html
{% extends "base_parking.html" %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/plate_search.css" %}">
{% endblock css %}
{% block content %}
    <h2>Resultado da busca</h2>
    <section>
        <div id="plate_search">
            <span>Motorista: {{ auto.driver }}</span>
            <span>Modelo: {{ auto.model }}</span>
            <span>Placa: {{ auto.autos_plate }}</span>
        </div>        
    </section>
{% endblock content %}

base_dir/templates/pre_finish.html
{% extends "base_parking.html" %}

{% block css %}
{% load static %}
<link rel="stylesheet" href="{% static "css/pre_finish.css" %}">
{% endblock css %}

{% block content %}
    <div id="parking_spaces">
        <span>Vaga {{ parking_space.id }}</span>
        <span>Horário de entrada: {{ checkin_datetime }}</span>
        <span>Horário de saída: {{ current_datetime }}</span>
        <span>{{ time_delta }}</span>
        <span>Total: R$ {{ price }}</span>
        <form action="{% url "apps:finish" parking_space.id parking_space.occupied_by.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Confirmar pagamento">
        </form>
    </div>
{% endblock content %}

base_dir/templates/registered_autos.html
{% extends "base_parking.html" %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/registered_drivers.css" %}">
{% endblock css %}

{% block content %}
    <h2>Automóveis cadastrados</h2>
    <section>
        <form action="{% url "apps:plate_search" %}" method="post">
            {% csrf_token %}
            Placa do veículo: {{ form.plate_search }}
            <input type="submit" value="Buscar">
        </form>
    </section>
    <section>
        {% for auto in all_registered_autos %}
            <div id="registered_drivers">
                <span>Motorista: {{ auto.driver }}</span>
                <span>Modelo: {{ auto.model }}</span>
                <span>Placa: {{ auto.autos_plate }}</span>
            </div>
        {% endfor %}
    </section>
{% endblock content %}

base_dir/templates/registered_drivers.html
{% extends "base_parking.html" %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/registered_drivers.css" %}">
{% endblock css %}

{% block content %}
    <h2>Motoristas cadastrados</h2>
    <section>
        <form action="{% url "apps:driver_search" %}" method="post">
            {% csrf_token %}
            Nome do motorista: {{ form.name_search }}
            <input type="submit" value="Buscar">
        </form>
    </section>
    <section>
        {% for driver in all_registered_drivers %}
            <div id="registered_drivers">
                <span>Nome: {{ driver.driver_name }}</span>
                <span>Mensalista: {{ driver.monthly }}</span>
                <span>CNH: {{ driver.cnh }}</span>
                <span>CPF: {{ driver.cpf }}</span>
            </div>
        {% endfor %}
    </section>
{% endblock content %}